### ISSUE TITLE
need update for openwrt master version

### ISSUE THREAD

**Issue by w01230** [openwrt-develop/luci-theme-atmaterial#3]
CSS needs update for latest openwrt/luci.

**Comment by panda-mute** [comment]
@w01230 please use branch dev for luci master/latest 18.06

**Comment by solidus1983** [comment]
Hi @panda-mute , sorry for re-opening this however, the theme is great but needs updating, there is issues with the theme where things such as Memory, Total Available, Free, Buffered area is not showing any progress bar, as well as tabs not working as its being shown on one whole page. 

I am currently using OpenWrt SNAPSHOT r9886 and i manually downloaded your files and placed them as per your script. So apart from the odd issues which might be .css based as the material theme updated greatly since the last version you used.

**Comment by panda-mute** [comment]
Please use the latest dev branch code.

**Comment by solidus1983** [comment]
I was using the latest version from Dev branch, however someone else made a fork and updated everything for OpenWRT 18.06.2 also from your Dev branch and corrected the issue and I decided to fork from that person and add some more code in to fix an icon issue. New to GitHub coding.
